name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t skir232232/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true skir232232/docker-react npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend2
          environment_name: Frontend2-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-076276934545
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip