name: Docker React CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v2

      # 2. Собираем образ (аналог before_install в Travis)
      - run: docker build -t skir232232/docker-react -f Dockerfile.dev .

      # 3. Запускаем тесты (аналог script в Travis)
      - run: docker run -e CI=true skir232232/docker-react npm run test