name: Docker React CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker-tests:
    name: Run Docker Tests
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Собираем образ (аналог before_install в Travis)
      - name: Build Docker image
        run: docker build -t skir232232/docker-react -f Dockerfile.dev .

      # 3. Запускаем тесты (аналог script в Travis)
      - name: Run tests in Docker
        run: docker run -e CI=true skir232232/docker-react npm run test